###############################################################################
# Copyright 2017 Samsung Electronics All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
###############################################################################

FROM java:8
MAINTAINER bg.chun@samsung.com

# If you don't need QEMU, please comment the below command. Otherwise, please refer to README file to use QEMU
COPY qemu-arm-static /usr/bin/qemu-arm-static

COPY target/device-opcua-java.jar /home/device-opcua-java.jar
COPY run.sh run.sh
EXPOSE 49997
CMD ["./run.sh"]
