FROM java:8
MAINTAINER bg.chun@samsung.com

# If you don't need QEMU, please comment the below command. Otherwise, please refer to README file to use QEMU
COPY qemu-arm-static /usr/bin/qemu-arm-static

COPY target/device-service-opcua.jar /home/device-service-opcua.jar
COPY run.sh run.sh
EXPOSE 49997
CMD ["./run.sh"]
